default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5

development:
  <<: *default
  database: app_development
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: app_test
  host: <%= ENV['DB_HOST'] %>
