test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  credentials: <%= Rails.application.credentials[:GCLOUD_KEY].as_json %> 
  project: "k41n3w-blog"
  bucket: "k41n3w-blog"